---
- name: Creating users
  hosts: webservers
  become: true

  tasks: 
  - name: Creating users
    user:
      name: "{{ item }}"
      state: present
    with_items:      
      - user10
      - user20
      - user30

