---
- name: Installing httpd
  hosts: webservers
  become: true

  tasks: 
  - name: Installing httpd packages
    yum:
       name: httpd
       state: installed
    when: ansible_os_family == "redhat"

  - name: starting httpd service 
    service:
      name: httpd
      state: started
    when: ansible_os_family == "redhat"

  - name: Installing apache2 packages
    apt:
      name: apache2
      state: present
    when: ansible_os_family == "debian"
        
  - name: starting apache2 service
    service: 
      name: apache2
      state: started
    when: ansible_os_family == "debian"

  - name: copy index.html file
    copy:
      src: /home/ansible/index.html
      dest: /var/www/html
      mode: 0666
  



