---
- name: uninstalling httpd
  hosts: webservers
  become: true

  tasks: 
  - name: uninstalling httpd packages
    yum:
       name: httpd
       state: removed
  - name: stop httpd service
    service: 
       name: httpd
       state: stopped




