---
- name: Installing httpd
  hosts: webservers
  become: true

  tasks: 
  - name: Installing httpd packages
    yum:
       name: httpd
       state: installed
  - name: starting httpd service
    service: 
       name: httpd
       state: started




